version: '3.8'
services:
  # postgresql://prisma:prisma@localhost:5401
  postgres:
    image: postgres:14
    container_name: templates-node-postgres
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    ports:
      - 5401:5432
    volumes:
      - ./scripts/:/docker-entrypoint-initdb.d/
