export const MusicStreamingServiceWithSqlserverWithReferentialIntegrityPrisma = [
  "\n\n-- CreateTable\nCREATE TABLE [dbo].[User] (\n    [id] NVARCHAR(1000) NOT NULL,\n    [createdAt] DATETIME2 NOT NULL CONSTRAINT [User_createdAt_df] DEFAULT CURRENT_TIMESTAMP,\n    [updatedAt] DATETIME2 NOT NULL,\n    [name] NVARCHAR(1000) NOT NULL,\n    [email] NVARCHAR(1000) NOT NULL,\n    CONSTRAINT [User_pkey] PRIMARY KEY ([id]),\n    CONSTRAINT [User_email_key] UNIQUE ([email])\n)",
  "\n\n-- CreateTable\nCREATE TABLE [dbo].[Interaction] (\n    [id] NVARCHAR(1000) NOT NULL,\n    [createdAt] DATETIME2 NOT NULL CONSTRAINT [Interaction_createdAt_df] DEFAULT CURRENT_TIMESTAMP,\n    [updatedAt] DATETIME2 NOT NULL,\n    [songId] NVARCHAR(1000),\n    [userId] NVARCHAR(1000),\n    [isLiked] BIT NOT NULL CONSTRAINT [Interaction_isLiked_df] DEFAULT 0,\n    [playCount] INT NOT NULL,\n    CONSTRAINT [Interaction_pkey] PRIMARY KEY ([id])\n)",
  "\n\n-- CreateTable\nCREATE TABLE [dbo].[Song] (\n    [id] NVARCHAR(1000) NOT NULL,\n    [createdAt] DATETIME2 NOT NULL CONSTRAINT [Song_createdAt_df] DEFAULT CURRENT_TIMESTAMP,\n    [updatedAt] DATETIME2 NOT NULL,\n    [name] NVARCHAR(1000) NOT NULL,\n    [albumId] NVARCHAR(1000),\n    [artistId] NVARCHAR(1000) NOT NULL,\n    [length] FLOAT(53) NOT NULL,\n    [track] INT,\n    [lyrics] NVARCHAR(1000),\n    [fileUrl] NVARCHAR(1000) NOT NULL,\n    CONSTRAINT [Song_pkey] PRIMARY KEY ([id])\n)",
  "\n\n-- CreateTable\nCREATE TABLE [dbo].[Artist] (\n    [id] NVARCHAR(1000) NOT NULL,\n    [createdAt] DATETIME2 NOT NULL CONSTRAINT [Artist_createdAt_df] DEFAULT CURRENT_TIMESTAMP,\n    [updatedAt] DATETIME2 NOT NULL,\n    [name] NVARCHAR(1000) NOT NULL,\n    CONSTRAINT [Artist_pkey] PRIMARY KEY ([id])\n)",
  "\n\n-- CreateTable\nCREATE TABLE [dbo].[Album] (\n    [id] NVARCHAR(1000) NOT NULL,\n    [createdAt] DATETIME2 NOT NULL CONSTRAINT [Album_createdAt_df] DEFAULT CURRENT_TIMESTAMP,\n    [updatedAt] DATETIME2 NOT NULL,\n    [name] NVARCHAR(1000) NOT NULL,\n    [cover] NVARCHAR(1000) NOT NULL,\n    CONSTRAINT [Album_pkey] PRIMARY KEY ([id])\n)",
  "\n\n-- CreateTable\nCREATE TABLE [dbo].[Playlist] (\n    [id] NVARCHAR(1000) NOT NULL,\n    [createdAt] DATETIME2 NOT NULL CONSTRAINT [Playlist_createdAt_df] DEFAULT CURRENT_TIMESTAMP,\n    [updatedAt] DATETIME2 NOT NULL,\n    [userId] NVARCHAR(1000),\n    [name] NVARCHAR(1000) NOT NULL,\n    CONSTRAINT [Playlist_pkey] PRIMARY KEY ([id])\n)",
  "\n\n-- CreateTable\nCREATE TABLE [dbo].[_AlbumToArtist] (\n    [A] NVARCHAR(1000) NOT NULL,\n    [B] NVARCHAR(1000) NOT NULL,\n    CONSTRAINT [_AlbumToArtist_AB_unique] UNIQUE ([A],[B])\n)",
  "\n\n-- CreateTable\nCREATE TABLE [dbo].[_PlaylistToSong] (\n    [A] NVARCHAR(1000) NOT NULL,\n    [B] NVARCHAR(1000) NOT NULL,\n    CONSTRAINT [_PlaylistToSong_AB_unique] UNIQUE ([A],[B])\n)",
  "\n\n-- CreateIndex\nCREATE INDEX [_AlbumToArtist_B_index] ON [dbo].[_AlbumToArtist]([B])",
  "\n\n-- CreateIndex\nCREATE INDEX [_PlaylistToSong_B_index] ON [dbo].[_PlaylistToSong]([B])"
]