export const MusicStreamingServiceWithPostgresWithReferentialIntegrityForeignKeys = [
  "-- CreateTable\nCREATE TABLE \"User\" (\n    \"id\" TEXT NOT NULL,\n    \"createdAt\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,\n    \"updatedAt\" TIMESTAMP(3) NOT NULL,\n    \"name\" TEXT NOT NULL,\n    \"email\" TEXT NOT NULL,\n\n    CONSTRAINT \"User_pkey\" PRIMARY KEY (\"id\")\n)",
  "\n\n-- CreateTable\nCREATE TABLE \"Interaction\" (\n    \"id\" TEXT NOT NULL,\n    \"createdAt\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,\n    \"updatedAt\" TIMESTAMP(3) NOT NULL,\n    \"songId\" TEXT,\n    \"userId\" TEXT,\n    \"isLiked\" BOOLEAN NOT NULL DEFAULT false,\n    \"playCount\" INTEGER NOT NULL,\n\n    CONSTRAINT \"Interaction_pkey\" PRIMARY KEY (\"id\")\n)",
  "\n\n-- CreateTable\nCREATE TABLE \"Song\" (\n    \"id\" TEXT NOT NULL,\n    \"createdAt\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,\n    \"updatedAt\" TIMESTAMP(3) NOT NULL,\n    \"name\" TEXT NOT NULL,\n    \"albumId\" TEXT,\n    \"artistId\" TEXT NOT NULL,\n    \"length\" DOUBLE PRECISION NOT NULL,\n    \"track\" INTEGER,\n    \"lyrics\" TEXT,\n    \"fileUrl\" TEXT NOT NULL,\n\n    CONSTRAINT \"Song_pkey\" PRIMARY KEY (\"id\")\n)",
  "\n\n-- CreateTable\nCREATE TABLE \"Artist\" (\n    \"id\" TEXT NOT NULL,\n    \"createdAt\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,\n    \"updatedAt\" TIMESTAMP(3) NOT NULL,\n    \"name\" TEXT NOT NULL,\n\n    CONSTRAINT \"Artist_pkey\" PRIMARY KEY (\"id\")\n)",
  "\n\n-- CreateTable\nCREATE TABLE \"Album\" (\n    \"id\" TEXT NOT NULL,\n    \"createdAt\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,\n    \"updatedAt\" TIMESTAMP(3) NOT NULL,\n    \"name\" TEXT NOT NULL,\n    \"cover\" TEXT NOT NULL,\n\n    CONSTRAINT \"Album_pkey\" PRIMARY KEY (\"id\")\n)",
  "\n\n-- CreateTable\nCREATE TABLE \"Playlist\" (\n    \"id\" TEXT NOT NULL,\n    \"createdAt\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,\n    \"updatedAt\" TIMESTAMP(3) NOT NULL,\n    \"userId\" TEXT,\n    \"name\" TEXT NOT NULL,\n\n    CONSTRAINT \"Playlist_pkey\" PRIMARY KEY (\"id\")\n)",
  "\n\n-- CreateTable\nCREATE TABLE \"_AlbumToArtist\" (\n    \"A\" TEXT NOT NULL,\n    \"B\" TEXT NOT NULL\n)",
  "\n\n-- CreateTable\nCREATE TABLE \"_PlaylistToSong\" (\n    \"A\" TEXT NOT NULL,\n    \"B\" TEXT NOT NULL\n)",
  "\n\n-- CreateIndex\nCREATE UNIQUE INDEX \"User_email_key\" ON \"User\"(\"email\")",
  "\n\n-- CreateIndex\nCREATE UNIQUE INDEX \"_AlbumToArtist_AB_unique\" ON \"_AlbumToArtist\"(\"A\", \"B\")",
  "\n\n-- CreateIndex\nCREATE INDEX \"_AlbumToArtist_B_index\" ON \"_AlbumToArtist\"(\"B\")",
  "\n\n-- CreateIndex\nCREATE UNIQUE INDEX \"_PlaylistToSong_AB_unique\" ON \"_PlaylistToSong\"(\"A\", \"B\")",
  "\n\n-- CreateIndex\nCREATE INDEX \"_PlaylistToSong_B_index\" ON \"_PlaylistToSong\"(\"B\")",
  "\n\n-- AddForeignKey\nALTER TABLE \"Interaction\" ADD CONSTRAINT \"Interaction_userId_fkey\" FOREIGN KEY (\"userId\") REFERENCES \"User\"(\"id\") ON DELETE SET NULL ON UPDATE CASCADE",
  "\n\n-- AddForeignKey\nALTER TABLE \"Interaction\" ADD CONSTRAINT \"Interaction_songId_fkey\" FOREIGN KEY (\"songId\") REFERENCES \"Song\"(\"id\") ON DELETE SET NULL ON UPDATE CASCADE",
  "\n\n-- AddForeignKey\nALTER TABLE \"Song\" ADD CONSTRAINT \"Song_artistId_fkey\" FOREIGN KEY (\"artistId\") REFERENCES \"Artist\"(\"id\") ON DELETE RESTRICT ON UPDATE CASCADE",
  "\n\n-- AddForeignKey\nALTER TABLE \"Song\" ADD CONSTRAINT \"Song_albumId_fkey\" FOREIGN KEY (\"albumId\") REFERENCES \"Album\"(\"id\") ON DELETE SET NULL ON UPDATE CASCADE",
  "\n\n-- AddForeignKey\nALTER TABLE \"Playlist\" ADD CONSTRAINT \"Playlist_userId_fkey\" FOREIGN KEY (\"userId\") REFERENCES \"User\"(\"id\") ON DELETE SET NULL ON UPDATE CASCADE",
  "\n\n-- AddForeignKey\nALTER TABLE \"_AlbumToArtist\" ADD FOREIGN KEY (\"A\") REFERENCES \"Album\"(\"id\") ON DELETE CASCADE ON UPDATE CASCADE",
  "\n\n-- AddForeignKey\nALTER TABLE \"_AlbumToArtist\" ADD FOREIGN KEY (\"B\") REFERENCES \"Artist\"(\"id\") ON DELETE CASCADE ON UPDATE CASCADE",
  "\n\n-- AddForeignKey\nALTER TABLE \"_PlaylistToSong\" ADD FOREIGN KEY (\"A\") REFERENCES \"Playlist\"(\"id\") ON DELETE CASCADE ON UPDATE CASCADE",
  "\n\n-- AddForeignKey\nALTER TABLE \"_PlaylistToSong\" ADD FOREIGN KEY (\"B\") REFERENCES \"Song\"(\"id\") ON DELETE CASCADE ON UPDATE CASCADE"
]