export const MusicStreamingServiceWithMysqlWithReferentialIntegrityForeignKeys = [
  "-- CreateTable\nCREATE TABLE User (\n    id VARCHAR(191) NOT NULL,\n    createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n    updatedAt DATETIME(3) NOT NULL,\n    name VARCHAR(191) NOT NULL,\n    email VARCHAR(191) NOT NULL,\n\n    UNIQUE INDEX User_email_key(email),\n    PRIMARY KEY (id)\n) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci",
  "\n\n-- CreateTable\nCREATE TABLE Interaction (\n    id VARCHAR(191) NOT NULL,\n    createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n    updatedAt DATETIME(3) NOT NULL,\n    songId VARCHAR(191) NULL,\n    userId VARCHAR(191) NULL,\n    isLiked BOOLEAN NOT NULL DEFAULT false,\n    playCount INTEGER NOT NULL,\n\n    PRIMARY KEY (id)\n) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci",
  "\n\n-- CreateTable\nCREATE TABLE Song (\n    id VARCHAR(191) NOT NULL,\n    createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n    updatedAt DATETIME(3) NOT NULL,\n    name VARCHAR(191) NOT NULL,\n    albumId VARCHAR(191) NULL,\n    artistId VARCHAR(191) NOT NULL,\n    length DOUBLE NOT NULL,\n    track INTEGER NULL,\n    lyrics VARCHAR(191) NULL,\n    fileUrl VARCHAR(191) NOT NULL,\n\n    PRIMARY KEY (id)\n) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci",
  "\n\n-- CreateTable\nCREATE TABLE Artist (\n    id VARCHAR(191) NOT NULL,\n    createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n    updatedAt DATETIME(3) NOT NULL,\n    name VARCHAR(191) NOT NULL,\n\n    PRIMARY KEY (id)\n) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci",
  "\n\n-- CreateTable\nCREATE TABLE Album (\n    id VARCHAR(191) NOT NULL,\n    createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n    updatedAt DATETIME(3) NOT NULL,\n    name VARCHAR(191) NOT NULL,\n    cover VARCHAR(191) NOT NULL,\n\n    PRIMARY KEY (id)\n) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci",
  "\n\n-- CreateTable\nCREATE TABLE Playlist (\n    id VARCHAR(191) NOT NULL,\n    createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n    updatedAt DATETIME(3) NOT NULL,\n    userId VARCHAR(191) NULL,\n    name VARCHAR(191) NOT NULL,\n\n    PRIMARY KEY (id)\n) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci",
  "\n\n-- CreateTable\nCREATE TABLE _AlbumToArtist (\n    A VARCHAR(191) NOT NULL,\n    B VARCHAR(191) NOT NULL,\n\n    UNIQUE INDEX _AlbumToArtist_AB_unique(A, B),\n    INDEX _AlbumToArtist_B_index(B)\n) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci",
  "\n\n-- CreateTable\nCREATE TABLE _PlaylistToSong (\n    A VARCHAR(191) NOT NULL,\n    B VARCHAR(191) NOT NULL,\n\n    UNIQUE INDEX _PlaylistToSong_AB_unique(A, B),\n    INDEX _PlaylistToSong_B_index(B)\n) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci",
  "\n\n-- AddForeignKey\nALTER TABLE Interaction ADD CONSTRAINT Interaction_userId_fkey FOREIGN KEY (userId) REFERENCES User(id) ON DELETE SET NULL ON UPDATE CASCADE",
  "\n\n-- AddForeignKey\nALTER TABLE Interaction ADD CONSTRAINT Interaction_songId_fkey FOREIGN KEY (songId) REFERENCES Song(id) ON DELETE SET NULL ON UPDATE CASCADE",
  "\n\n-- AddForeignKey\nALTER TABLE Song ADD CONSTRAINT Song_artistId_fkey FOREIGN KEY (artistId) REFERENCES Artist(id) ON DELETE RESTRICT ON UPDATE CASCADE",
  "\n\n-- AddForeignKey\nALTER TABLE Song ADD CONSTRAINT Song_albumId_fkey FOREIGN KEY (albumId) REFERENCES Album(id) ON DELETE SET NULL ON UPDATE CASCADE",
  "\n\n-- AddForeignKey\nALTER TABLE Playlist ADD CONSTRAINT Playlist_userId_fkey FOREIGN KEY (userId) REFERENCES User(id) ON DELETE SET NULL ON UPDATE CASCADE",
  "\n\n-- AddForeignKey\nALTER TABLE _AlbumToArtist ADD FOREIGN KEY (A) REFERENCES Album(id) ON DELETE CASCADE ON UPDATE CASCADE",
  "\n\n-- AddForeignKey\nALTER TABLE _AlbumToArtist ADD FOREIGN KEY (B) REFERENCES Artist(id) ON DELETE CASCADE ON UPDATE CASCADE",
  "\n\n-- AddForeignKey\nALTER TABLE _PlaylistToSong ADD FOREIGN KEY (A) REFERENCES Playlist(id) ON DELETE CASCADE ON UPDATE CASCADE",
  "\n\n-- AddForeignKey\nALTER TABLE _PlaylistToSong ADD FOREIGN KEY (B) REFERENCES Song(id) ON DELETE CASCADE ON UPDATE CASCADE"
]