export const RentalsPlatformWithPostgresWithReferentialIntegrityForeignKeys = [
  "-- CreateTable\nCREATE TABLE \"User\" (\n    \"id\" TEXT NOT NULL,\n    \"createdAt\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,\n    \"updatedAt\" TIMESTAMP(3) NOT NULL,\n    \"email\" TEXT NOT NULL,\n    \"name\" TEXT NOT NULL,\n\n    CONSTRAINT \"User_pkey\" PRIMARY KEY (\"id\")\n)",
  "\n\n-- CreateTable\nCREATE TABLE \"Reservation\" (\n    \"id\" TEXT NOT NULL,\n    \"createdAt\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,\n    \"updatedAt\" TIMESTAMP(3) NOT NULL,\n    \"userId\" TEXT,\n    \"startDate\" TIMESTAMP(3) NOT NULL,\n    \"endDate\" TIMESTAMP(3) NOT NULL,\n    \"price\" INTEGER NOT NULL,\n    \"total\" INTEGER NOT NULL,\n    \"roomId\" TEXT,\n\n    CONSTRAINT \"Reservation_pkey\" PRIMARY KEY (\"id\")\n)",
  "\n\n-- CreateTable\nCREATE TABLE \"Room\" (\n    \"id\" TEXT NOT NULL,\n    \"createdAt\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,\n    \"updatedAt\" TIMESTAMP(3) NOT NULL,\n    \"totalOccupancy\" INTEGER NOT NULL DEFAULT 5,\n    \"totalBedrooms\" INTEGER NOT NULL DEFAULT 5,\n    \"totalBathrooms\" INTEGER NOT NULL DEFAULT 5,\n    \"summary\" TEXT,\n    \"address\" TEXT NOT NULL,\n    \"isSmoking\" BOOLEAN NOT NULL DEFAULT false,\n    \"hasTV\" BOOLEAN NOT NULL DEFAULT true,\n    \"hasAirConditioning\" BOOLEAN NOT NULL DEFAULT true,\n    \"hasHeating\" BOOLEAN NOT NULL DEFAULT true,\n    \"hasWIFI\" BOOLEAN NOT NULL DEFAULT true,\n    \"price\" INTEGER NOT NULL,\n\n    CONSTRAINT \"Room_pkey\" PRIMARY KEY (\"id\")\n)",
  "\n\n-- CreateTable\nCREATE TABLE \"Review\" (\n    \"id\" TEXT NOT NULL,\n    \"createdAt\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,\n    \"updatedAt\" TIMESTAMP(3) NOT NULL,\n    \"rating\" INTEGER NOT NULL,\n    \"comment\" TEXT NOT NULL,\n    \"userId\" TEXT NOT NULL,\n\n    CONSTRAINT \"Review_pkey\" PRIMARY KEY (\"id\")\n)",
  "\n\n-- CreateTable\nCREATE TABLE \"Media\" (\n    \"id\" TEXT NOT NULL,\n    \"createdAt\" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,\n    \"updatedAt\" TIMESTAMP(3) NOT NULL,\n    \"roomId\" TEXT,\n    \"fileName\" TEXT NOT NULL,\n\n    CONSTRAINT \"Media_pkey\" PRIMARY KEY (\"id\")\n)",
  "\n\n-- CreateIndex\nCREATE UNIQUE INDEX \"User_email_key\" ON \"User\"(\"email\")",
  "\n\n-- AddForeignKey\nALTER TABLE \"Reservation\" ADD CONSTRAINT \"Reservation_userId_fkey\" FOREIGN KEY (\"userId\") REFERENCES \"User\"(\"id\") ON DELETE SET NULL ON UPDATE CASCADE",
  "\n\n-- AddForeignKey\nALTER TABLE \"Reservation\" ADD CONSTRAINT \"Reservation_roomId_fkey\" FOREIGN KEY (\"roomId\") REFERENCES \"Room\"(\"id\") ON DELETE SET NULL ON UPDATE CASCADE",
  "\n\n-- AddForeignKey\nALTER TABLE \"Review\" ADD CONSTRAINT \"Review_userId_fkey\" FOREIGN KEY (\"userId\") REFERENCES \"User\"(\"id\") ON DELETE RESTRICT ON UPDATE CASCADE",
  "\n\n-- AddForeignKey\nALTER TABLE \"Media\" ADD CONSTRAINT \"Media_roomId_fkey\" FOREIGN KEY (\"roomId\") REFERENCES \"Room\"(\"id\") ON DELETE SET NULL ON UPDATE CASCADE"
]