export const RentalsPlatformWithSqlserverWithReferentialIntegrityForeignKeys = [
  "\n\n-- CreateTable\nCREATE TABLE [dbo].[User] (\n    [id] NVARCHAR(1000) NOT NULL,\n    [createdAt] DATETIME2 NOT NULL CONSTRAINT [User_createdAt_df] DEFAULT CURRENT_TIMESTAMP,\n    [updatedAt] DATETIME2 NOT NULL,\n    [email] NVARCHAR(1000) NOT NULL,\n    [name] NVARCHAR(1000) NOT NULL,\n    CONSTRAINT [User_pkey] PRIMARY KEY ([id]),\n    CONSTRAINT [User_email_key] UNIQUE ([email])\n)",
  "\n\n-- CreateTable\nCREATE TABLE [dbo].[Reservation] (\n    [id] NVARCHAR(1000) NOT NULL,\n    [createdAt] DATETIME2 NOT NULL CONSTRAINT [Reservation_createdAt_df] DEFAULT CURRENT_TIMESTAMP,\n    [updatedAt] DATETIME2 NOT NULL,\n    [userId] NVARCHAR(1000),\n    [startDate] DATETIME2 NOT NULL,\n    [endDate] DATETIME2 NOT NULL,\n    [price] INT NOT NULL,\n    [total] INT NOT NULL,\n    [roomId] NVARCHAR(1000),\n    CONSTRAINT [Reservation_pkey] PRIMARY KEY ([id])\n)",
  "\n\n-- CreateTable\nCREATE TABLE [dbo].[Room] (\n    [id] NVARCHAR(1000) NOT NULL,\n    [createdAt] DATETIME2 NOT NULL CONSTRAINT [Room_createdAt_df] DEFAULT CURRENT_TIMESTAMP,\n    [updatedAt] DATETIME2 NOT NULL,\n    [totalOccupancy] INT NOT NULL CONSTRAINT [Room_totalOccupancy_df] DEFAULT 5,\n    [totalBedrooms] INT NOT NULL CONSTRAINT [Room_totalBedrooms_df] DEFAULT 5,\n    [totalBathrooms] INT NOT NULL CONSTRAINT [Room_totalBathrooms_df] DEFAULT 5,\n    [summary] NVARCHAR(1000),\n    [address] NVARCHAR(1000) NOT NULL,\n    [isSmoking] BIT NOT NULL CONSTRAINT [Room_isSmoking_df] DEFAULT 0,\n    [hasTV] BIT NOT NULL CONSTRAINT [Room_hasTV_df] DEFAULT 1,\n    [hasAirConditioning] BIT NOT NULL CONSTRAINT [Room_hasAirConditioning_df] DEFAULT 1,\n    [hasHeating] BIT NOT NULL CONSTRAINT [Room_hasHeating_df] DEFAULT 1,\n    [hasWIFI] BIT NOT NULL CONSTRAINT [Room_hasWIFI_df] DEFAULT 1,\n    [price] INT NOT NULL,\n    CONSTRAINT [Room_pkey] PRIMARY KEY ([id])\n)",
  "\n\n-- CreateTable\nCREATE TABLE [dbo].[Review] (\n    [id] NVARCHAR(1000) NOT NULL,\n    [createdAt] DATETIME2 NOT NULL CONSTRAINT [Review_createdAt_df] DEFAULT CURRENT_TIMESTAMP,\n    [updatedAt] DATETIME2 NOT NULL,\n    [rating] INT NOT NULL,\n    [comment] NVARCHAR(1000) NOT NULL,\n    [userId] NVARCHAR(1000) NOT NULL,\n    CONSTRAINT [Review_pkey] PRIMARY KEY ([id])\n)",
  "\n\n-- CreateTable\nCREATE TABLE [dbo].[Media] (\n    [id] NVARCHAR(1000) NOT NULL,\n    [createdAt] DATETIME2 NOT NULL CONSTRAINT [Media_createdAt_df] DEFAULT CURRENT_TIMESTAMP,\n    [updatedAt] DATETIME2 NOT NULL,\n    [roomId] NVARCHAR(1000),\n    [fileName] NVARCHAR(1000) NOT NULL,\n    CONSTRAINT [Media_pkey] PRIMARY KEY ([id])\n)",
  "\n\n-- AddForeignKey\nALTER TABLE [dbo].[Reservation] ADD CONSTRAINT [Reservation_userId_fkey] FOREIGN KEY ([userId]) REFERENCES [dbo].[User]([id]) ON DELETE SET NULL ON UPDATE CASCADE",
  "\n\n-- AddForeignKey\nALTER TABLE [dbo].[Reservation] ADD CONSTRAINT [Reservation_roomId_fkey] FOREIGN KEY ([roomId]) REFERENCES [dbo].[Room]([id]) ON DELETE SET NULL ON UPDATE CASCADE",
  "\n\n-- AddForeignKey\nALTER TABLE [dbo].[Review] ADD CONSTRAINT [Review_userId_fkey] FOREIGN KEY ([userId]) REFERENCES [dbo].[User]([id]) ON DELETE NO ACTION ON UPDATE CASCADE",
  "\n\n-- AddForeignKey\nALTER TABLE [dbo].[Media] ADD CONSTRAINT [Media_roomId_fkey] FOREIGN KEY ([roomId]) REFERENCES [dbo].[Room]([id]) ON DELETE SET NULL ON UPDATE CASCADE"
]