export const RentalsPlatformWithMysqlWithReferentialIntegrityForeignKeys = [
  "-- CreateTable\nCREATE TABLE User (\n    id VARCHAR(191) NOT NULL,\n    createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n    updatedAt DATETIME(3) NOT NULL,\n    email VARCHAR(191) NOT NULL,\n    name VARCHAR(191) NOT NULL,\n\n    UNIQUE INDEX User_email_key(email),\n    PRIMARY KEY (id)\n) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci",
  "\n\n-- CreateTable\nCREATE TABLE Reservation (\n    id VARCHAR(191) NOT NULL,\n    createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n    updatedAt DATETIME(3) NOT NULL,\n    userId VARCHAR(191) NULL,\n    startDate DATETIME(3) NOT NULL,\n    endDate DATETIME(3) NOT NULL,\n    price INTEGER NOT NULL,\n    total INTEGER NOT NULL,\n    roomId VARCHAR(191) NULL,\n\n    PRIMARY KEY (id)\n) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci",
  "\n\n-- CreateTable\nCREATE TABLE Room (\n    id VARCHAR(191) NOT NULL,\n    createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n    updatedAt DATETIME(3) NOT NULL,\n    totalOccupancy INTEGER NOT NULL DEFAULT 5,\n    totalBedrooms INTEGER NOT NULL DEFAULT 5,\n    totalBathrooms INTEGER NOT NULL DEFAULT 5,\n    summary VARCHAR(191) NULL,\n    address VARCHAR(191) NOT NULL,\n    isSmoking BOOLEAN NOT NULL DEFAULT false,\n    hasTV BOOLEAN NOT NULL DEFAULT true,\n    hasAirConditioning BOOLEAN NOT NULL DEFAULT true,\n    hasHeating BOOLEAN NOT NULL DEFAULT true,\n    hasWIFI BOOLEAN NOT NULL DEFAULT true,\n    price INTEGER NOT NULL,\n\n    PRIMARY KEY (id)\n) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci",
  "\n\n-- CreateTable\nCREATE TABLE Review (\n    id VARCHAR(191) NOT NULL,\n    createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n    updatedAt DATETIME(3) NOT NULL,\n    rating INTEGER NOT NULL,\n    comment VARCHAR(191) NOT NULL,\n    userId VARCHAR(191) NOT NULL,\n\n    PRIMARY KEY (id)\n) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci",
  "\n\n-- CreateTable\nCREATE TABLE Media (\n    id VARCHAR(191) NOT NULL,\n    createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),\n    updatedAt DATETIME(3) NOT NULL,\n    roomId VARCHAR(191) NULL,\n    fileName VARCHAR(191) NOT NULL,\n\n    PRIMARY KEY (id)\n) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci",
  "\n\n-- AddForeignKey\nALTER TABLE Reservation ADD CONSTRAINT Reservation_userId_fkey FOREIGN KEY (userId) REFERENCES User(id) ON DELETE SET NULL ON UPDATE CASCADE",
  "\n\n-- AddForeignKey\nALTER TABLE Reservation ADD CONSTRAINT Reservation_roomId_fkey FOREIGN KEY (roomId) REFERENCES Room(id) ON DELETE SET NULL ON UPDATE CASCADE",
  "\n\n-- AddForeignKey\nALTER TABLE Review ADD CONSTRAINT Review_userId_fkey FOREIGN KEY (userId) REFERENCES User(id) ON DELETE RESTRICT ON UPDATE CASCADE",
  "\n\n-- AddForeignKey\nALTER TABLE Media ADD CONSTRAINT Media_roomId_fkey FOREIGN KEY (roomId) REFERENCES Room(id) ON DELETE SET NULL ON UPDATE CASCADE"
]