name: pr

on:
  - pull_request

jobs:
  format-imports:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn
      - name: Install Dependencies
        run: yarn --frozen-lockfile
      - run: yarn -s format:check:imports

  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn
      - name: Install Dependencies
        run: yarn --frozen-lockfile
      - run: yarn -s format:check:prettier

  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn
      - run: yarn --frozen-lockfile
      - run: yarn -s build:gen && yarn -s type-check

  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn
      - name: Install Dependencies
        run: yarn --frozen-lockfile
      - run: yarn -s build:gen
      - run: yarn -s lint:check

  test:
    strategy:
      matrix:
        os: ['ubuntu-latest']
        node-version: [14.x, 16.x]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - run: yarn --frozen-lockfile
      - run: yarn -s build:gen && yarn -s test
