name: test
on:
  - workflow_call
jobs:
  test-workflow:
    strategy:
      matrix:
        os: ['ubuntu-latest']
        node-version: [16.x, 18.x]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Test a simple echo
        run: echo "Testing workflow secret"
      - name: Test a secret echo
        with:
          psTestDBURI: ${{secrets.PLANET_SCALE_TEST_DB_URI}}
        run: echo "uri:$psTestDBURI"
