name: test
on:
  - workflow_call
env:
  PLANET_SCALE_TEST_DB_URI: ${{ secrets.PLANET_SCALE_TEST_DB_URI }}
jobs:
  test-workflow:
    strategy:
      matrix:
        os: ['ubuntu-latest']
        node-version: [16.x, 18.x]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Test a simple echo
        run: echo "Testing workflow secret I"
      - name: Test a secret echo
        with:
          super_secret: ${{ secrets.PLANET_SCALE_TEST_DB_URI }}
        run: echo "Testing workflow secret II"
