name: test
on:
  - workflow_call
jobs:
  test-e2e:
    strategy:
      matrix:
        os: ['ubuntu-latest']
        node-version: [16.x, 18.x]
        db: [postgres, vitess-no-foreign-keys]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - run: docker-compose up --detach ${{ matrix.db }}
      - run: echo "Planet Scale test  "
      - run: echo ${{ secrets.PLANET_SCALE_TEST_DB_URI }}
      - uses: prisma/action-node-cache-dependencies@main
      - uses: ./.github/actions/generateTemplates
      - run: yarn -s test e2e/${{ matrix.db }}
