name: trunk
on:
  push:
    branches: [main]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - uses: prisma/action-node-cache-dependencies@main
  test-unit:
    strategy:
      matrix:
        os: ['ubuntu-latest']
        node-version: [14.x, 16.x]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - uses: prisma/action-node-cache-dependencies@main
      - uses: ./.github/actions/generateTemplates
      - run: yarn -s test:unit
  release-canary:
    runs-on: ubuntu-latest
    needs: [test-unit]
    steps:
      - uses: prisma-labs/dripip@master
        with:
          npmToken: ${{secrets.NPM_TOKEN}}
          githubToken: ${{secrets.GITHUB_TOKEN}}
