name: trunk

on:
  push:
    branches: [main]

jobs:
  test:
    strategy:
      matrix:
        os: ['ubuntu-latest']
        node-version: [14.x, 16.x]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - name: Install Dependencies
        run: yarn --frozen-lockfile
      - run: yarn -s build:gen && yarn -s test

  release-canary:
    needs: [test]
    uses: prisma-labs/dripip/.github/workflows/release.yml@main
    secrets:
      npmToken: ${{secrets.NPM_TOKEN}}
      githubToken: ${{secrets.GITHUB_TOKEN}}
