name: trunk
on:
  push:
    branches: [main]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - uses: prisma/action-node-cache-dependencies@main
  test-unit:
    needs: setup
    uses: ./.github/workflows/test-unit.yml
  test-e2e:
    needs: setup
    uses: ./.github/workflows/test-e2e.yml
  release-canary:
    runs-on: ubuntu-latest
    needs: [test-unit, test-e2e]
    steps:
      - uses: prisma-labs/dripip@master
        with:
          npmToken: ${{secrets.NPM_TOKEN}}
          githubToken: ${{secrets.GITHUB_TOKEN}}
